name: Gh Pages

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  heroku-cd:
    name: 📄 Publish Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 🌳 tree
        run: tree

      - name: 📢 Publish Page
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: server-release
          folder: server

  deploy:
    name: 📄 Publish Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 🌳 tree
        run: tree

      - name: 📢 Publish Page
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: frontend
