name: Gh Pages

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy-to-heroku:
    name: 📄 Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 🌳 tree
        run: tree

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: ra-p-api
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          userdocker: true

  deploy-to-gh-pages:
    name: 📄 Publish Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 🌳 tree
        run: tree

      - name: 📢 Publish Page
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: frontend
